### ISSUE TITLE
Reasoning for removing Actor data access layer? 

### ISSUE THREAD

**Issue by bthibault** [cdiniz/spray-slick-swagger#3]
Hi, 

can you provide the reason for removing the Akka Actors providing the persistence layer ? 

Thanks

**Comment by cdiniz** [comment]
Hi,

I did performance/load tests and the version without actors was performed a little better. So I have decided to keep the template without actors, since, without actors the template became easier to get, or to adapt. I kept the branch 0.0.1 for testing and debugging this situation.
